# HK

net.ipv4.tcp_wmem = 4096 65536 2097152
net.ipv4.tcp_rmem = 4096 65536 16777216
net.ipv4.tcp_congestion_control = bbr
net.core.default_qdisc = fq

# US

net.ipv4.tcp_wmem = 4096 65536 16777216
net.ipv4.tcp_rmem = 4096 65536 2097152
net.ipv4.tcp_congestion_control = bbr
net.core.default_qdisc = fq
